notifications:
    email: false

language: objective-c

compiler:
    - gcc

before_install:
    - brew help 
    - brew list 
    - brew update 
    
before_script:
    - chmod -R +x .

script: 
    - make